name: Bug Report
description: Báo lỗi trong ứng dụng quay số
title: "[BUG]: "
labels: [bug]

body:
  - type: textarea
    attributes:
      label: Mô tả lỗi
  - type: textarea
    attributes:
      label: Cách tái hiện lỗi
  - type: textarea
    attributes:
      label: Kết quả mong đợi
  - type: textarea
    attributes:
      label: Log console (nếu có)
